name: DatSoup
version: 1.0
main: com.souppvp.Main
api-version: 1.8
author: lvnah
commands:
  help:
    description: Affiche l'aide du serveur DatSoup.
  setspawn:
    description: Definit le spawn principal.
  setarenespawn:
    description: Definit le spawn de l'arene FFA.
  set1v1spawn1:
    description: Definit le premier spawn 1v1.
  set1v1spawn2:
    description: Definit le second spawn 1v1.
  settournoispawn:
    description: Ajoute un spawn de tournoi.
  menu:
    description: Ouvre le menu principal.
  queue1v1:
    description: Rejoindre la file d'attente 1v1.
  tournoi:
    description: Gestion du tournoi.
  sb:
    description: Afficher/Masquer le scoreboard.
  scoreboard:
    description: Afficher/Masquer le scoreboard.
  setrank:
    description: Definir le grade d'un joueur.
    permission: souppvp.admin
