name: SoupTournament
version: 1.0
main: com.souppvp.Main
author: DatSoup
api-version: 1.8

commands:
  warps:
    description: Ouvre le menu des warps
    aliases: [menu]
  menu:
    description: Ouvre le menu des warps
  queue1v1:
    description: Rejoint la file 1v1
  stats:
    description: Affiche tes statistiques
  help:
    description: Affiche le menu d'aide
  sb:
    description: Masque ou affiche le scoreboard
    aliases: [scoreboard]
  scoreboard:
    description: Masque ou affiche le scoreboard
  tournoi:
    description: Commande pour les tournois
  build:
    description: Active ou desactive le mode construction
    permission: souppvp.admin
  setspawn:
    description: Definit le spawn principal
    permission: souppvp.admin
  setffaspawn:
    description: Definit le spawn FFA
    permission: souppvp.admin
  setearlyhgspawn:
    description: Definit le spawn EarlyHG
    permission: souppvp.admin
  setchallengespawn:
    description: Definit le spawn Challenge
    permission: souppvp.admin
  set1v1spawn1:
    description: Definit le 1er spawn 1v1
    permission: souppvp.admin
  set1v1spawn2:
    description: Definit le 2eme spawn 1v1
    permission: souppvp.admin
  settournoispawn:
    description: Ajoute un spawn de tournoi
    permission: souppvp.admin
  setrank:
    description: Change le grade d'un joueur
    permission: souppvp.admin